### ISSUE TITLE
customization todo list

### ISSUE THREAD

**Issue by tekunotri** [tekunotri/technohud#2]
- [x] streamline hud damage position + make color customizable 
- [x] streamline ammo clip/reserve/noammo colors to make them fully customizable as the user sees fit
- [x] chat position customization

more things will be added as i think them up or recieve feedback
